import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import useSWR from 'swr'
import type { Item } from '../data'

const fetcher = (url: string) => fetch(url).then((res) => res.json())

const Home = () => {
  const { data, error } = useSWR<Item[]>('/api/items', fetcher)

  if (error) return <div>Failed to load</div>
  if (!data) return <div>Loading...</div>

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>
        <div>
          {data.map((item) => (
            <div key={item.id}>
              <Link href="/items/[id]" as={`/items/${item.id}`}>{item.content}</Link>
            </div>
          ))}
        </div>
      </main>

      <footer className="container mx-auto px-6">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className="h-4 ml-2">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  )
}

export default Home
