import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import useSWR from 'swr'
import type { IItem } from '../data'
import Nav from '../components/Nav'
import Footer from '../components/Footer'

const fetcher = (url: string) => fetch(url).then((res) => res.json())

const Home = () => {
  const { data, error } = useSWR<IItem[]>('/api/items', fetcher)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container grow py-10">
        {error ? (
          <div>Failed to load</div>
        ) : !data ? (
          <div>Loading...</div>
        ) : (
          <>
            <Nav items={[{ text: 'Home' }]} />
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-x-1 gap-y-1">
              {data.map((item) => (
                <Link key={item.id} href="/items/[id]" as={`/items/${item.id}`}>
                  <div className="relative rounded-lg cursor-pointer">
                    {item.media.slice(0, 1).map((img, i) => (
                      <div key={i}>
                        <Image src={img.url} width={img.width} height={img.height} className="rounded-lg" />
                        <h4 className="text-white md:text-lg font-bold absolute left-0 bottom-0 pb-4 px-4">{item.title}</h4>
                      </div>
                    ))}
                  </div>
                </Link>
              ))}
            </div>
          </>
        )}
      </main>

      <Footer />
    </>
  )
}

export default Home
